"""
Django settings for Jba project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from whitenoise import WhiteNoise
import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialise environment variables
env_file=os.path.join(BASE_DIR,'.env');
env = environ.Env()
env.read_env(env_file)

DEBUG = env('DEBUG')
SECRET_KEY = env('SECRET_KEY')
ALLOWED_HOSTS = [
    '*'
]

#----------------------------
# Application definition
#----------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'whitenoise.runserver_nostatic',
    'Jbooka.apps.JbookaConfig',
    'users.apps.UsersConfig',
    'feed.apps.FeedConfig',
    'crispy_forms',
    'paypal.standard.ipn',
    'sorl.thumbnail',
    'tailwind',
    'theme',
    'django_browser_reload',
    'widget_tweaks',
    'ckeditor',
    'tagify',
]

#----------------------------
##  TAILWIND CSS CONFIGURATION ##
#----------------------------
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]
NPM_BIN_PATH = env('NPM_BIN_PATH')

#----------------------------
# settings
#----------------------------

##  CKEDITOR CONFIGURATION ##
CKEDITOR_CONFIGS = {
    'default': {
        'width': 630,
        'height': 150,
        'toolbar': 'Custom',
       
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['Font', 'FontSize','TextColor', 'BGColor'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        ],
    
    },
}

<<<<<<< HEAD
#----------------------------                                                                                                                             
=======
#----------------------------
>>>>>>> 3f7d2b6988d102b94035989cbb1eec72e836ea7c
# MIDDLEWARE
#----------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',                                                                                             
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'Jba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR / 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'Jba.wsgi.application'


#----------------------------
# Database
#----------------------------

<<<<<<< HEAD
# # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': env('DATABASE_ENGINE'),
#         'NAME': env('DATABASE_NAME'),
#         'USER': env('DATABASE_USER'),
#         'PASSWORD': env('DATABASE_PASS'),
#         'HOST': env("DATABASE_HOST"),
#         'PORT': env("DATABASE_PORT")
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3', 
=======
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASS'),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT")
>>>>>>> 3f7d2b6988d102b94035989cbb1eec72e836ea7c
    }
}



#----------------------------
# Password validation
#----------------------------
<<<<<<< HEAD
=======

# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
>>>>>>> 3f7d2b6988d102b94035989cbb1eec72e836ea7c

# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
                                                                                                                                                          
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#----------------------------
# Internationalization
#----------------------------

# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

#----------------------------
# Static files (CSS, JavaScript, Images)
#----------------------------

# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Whitenoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

#----------------------------
# SMTP Configuration
#----------------------------

EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

#----------------------------
#  PAYPAL CONFIGURATION #
#----------------------------

# the email used to create the PayPal account
PAYPAL_RECEIVER_EMAIL = env('PAYPAL_RECEIVER_EMAIL')

# is a boolean value sandbox account is used to test things
PAYPAL_TEST = True



#----------------------------
#
#----------------------------

# session settings
CART_SESSION_ID = 'cart'

#----------------------------
#
#----------------------------

# Toggle sandbox mode (when running in DEBUG mode)
SENDGRID_SANDBOX_MODE_IN_DEBUG=False

#----------------------------
# 
#----------------------------

# echo to stdout or any other file-like object that is passed to the backend via the stream kwarg.
SENDGRID_ECHO_TO_STDOUT=True

#----------------------------
# Configure CORS settings for cross-origin resource sharing.
#----------------------------
<<<<<<< HEAD
CORS_ORIGIN_ALLOW_ALL = True                                                                                                                              
=======
CORS_ORIGIN_ALLOW_ALL = True
>>>>>>> 3f7d2b6988d102b94035989cbb1eec72e836ea7c

