name: hello world workflows

on: 
  push:
    branches:
      - c_feature
    pull_request:
      - c_feature
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        name: hello world
        run: echo "hello world"
        shell: bash


